### ISSUE TITLE
imx_usb and imx6ul doesn't work

### ISSUE THREAD

**Issue by Oleh-Kravchenko** [boundarydevices/imx_usb_loader#57] opened 2017-01-31 15:39 UTC
I used "git bisect" and find commit 6deb910dd0a64267c43e65e95486f975e293823f break booting.

Output:
config file </tmp/root/etc/imx-loader.d//imx_usb.conf>
vid=0x066f pid=0x3780 file_name=mx23_usb_work.conf
vid=0x15a2 pid=0x004f file_name=mx28_usb_work.conf
vid=0x15a2 pid=0x0052 file_name=mx50_usb_work.conf
vid=0x15a2 pid=0x0054 file_name=mx6_usb_work.conf
vid=0x15a2 pid=0x0061 file_name=mx6_usb_work.conf
vid=0x15a2 pid=0x0063 file_name=mx6_usb_work.conf
vid=0x15a2 pid=0x0071 file_name=mx6_usb_work.conf
vid=0x15a2 pid=0x007d file_name=mx6_usb_work.conf
vid=0x15a2 pid=0x0076 file_name=mx7_usb_work.conf
vid=0x15a2 pid=0x0041 file_name=mx51_usb_work.conf
vid=0x15a2 pid=0x004e file_name=mx53_usb_work.conf
vid=0x15a2 pid=0x006a file_name=vybrid_usb_work.conf
vid=0x066f pid=0x37ff file_name=linux_gadget.conf
config file </tmp/root/etc/imx-loader.d//mx6_usb_work.conf>
parse /tmp/root/etc/imx-loader.d//mx6_usb_work.conf
Interface 0 claimed
HAB security state: development mode (0x56787856)
== work item
filename /home/kaa/projects/uboot-imx6_ul/u-boot.imx
load_size 0 bytes
load_addr 0x00000000
dcd 1
clear_dcd 0
plug 1
jump_mode 2
jump_addr 0x00000000
== end work item
loading DCD table @0x910000

<<<-528, 1024 bytes>>>
succeeded (status 0x128a8a12)

loading binary file(/home/kaa/projects/uboot-imx6_ul/u-boot.imx) to 877ff400, skip=0, fsize=59c00 type=aa
out err=-7, last_trans=0 cnt=0x4000 max=0x400 transferSize=0x0 retry=0
out err=-7, last_trans=0 cnt=0x4000 max=0x200 transferSize=0x0 retry=1
out err=-7, last_trans=0 cnt=0x4000 max=0x100 transferSize=0x0 retry=2
out err=-7, last_trans=0 cnt=0x4000 max=0x80 transferSize=0x0 retry=3
out err=-7, last_trans=0 cnt=0x4000 max=0x40 transferSize=0x0 retry=4
out err=-7, last_trans=0 cnt=0x4000 max=0x20 transferSize=0x0 retry=5
out err=-7, last_trans=0 cnt=0x4000 max=0x10 transferSize=0x0 retry=6
out err=-7, last_trans=0 cnt=0x4000 max=0x8 transferSize=0x0 retry=7
out err=-7, last_trans=0 cnt=0x4000 max=0x10 transferSize=0x0 retry=8
out err=-7, last_trans=0 cnt=0x4000 max=0x8 transferSize=0x0 retry=9
out err=-7, last_trans=0 cnt=0x4000 max=0x10 transferSize=0x0 retry=10
Giving up
DoIRomDownload failed, err=-7
HAB security state: development mode (0x00000000)

**Comment by gibsson** [comment] 2017-02-27 15:36
Hi,

Unfortunately we don't have any i.MX6UL platform to test with. Can you offer a patch?

Are you sure the issue isn't just the DCD loading address which can be modified form the conf file?

We can't revert the patch you mentioned since it is absolutely required for HAB support which is very important.

Regards,
Gary

**Comment by duncanfinney** [comment] 2017-03-15 16:11
+1 I'm experiencing the same issue.

**Comment by gibsson** [comment] 2017-03-17 08:45
Hi,

The DCD table seems to be loaded at the correct address. Not sure what isn't working and unfortunately we still have no i.MX6UL board to test against. Again, patches are welcome.

In the meantime, you can test and compare with mfgtools:
https://github.com/NXPmicro/mfgtools

Regards,
Gary

**Comment by gibsson** [comment] 2017-04-10 15:46
Hi,

Closing this issue since someone confirmed that it works for both i.MX6UL and i.MX6ULL.

Regards,
Gary

**Closed by gibsson** 2017-04-10 15:46 UTC

**Comment by TonyTarakan** [comment] 2017-12-27 09:31
Hello!
I faced with the same issue. Commit [138c0b25](https://github.com/boundarydevices/imx_usb_loader/commit/138c0b25a4df6bc25567882ba80337543c22fd93)

> $ sudo ./imx_usb ../u-boot/u-boot.imx
> config file <.//imx_usb.conf>
> vid=0x066f pid=0x3780 file_name=mx23_usb_work.conf
> vid=0x15a2 pid=0x004f file_name=mx28_usb_work.conf
> vid=0x15a2 pid=0x0052 file_name=mx50_usb_work.conf
> vid=0x15a2 pid=0x0054 file_name=mx6_usb_work.conf
> vid=0x15a2 pid=0x0061 file_name=mx6_usb_work.conf
> vid=0x15a2 pid=0x0063 file_name=mx6_usb_work.conf
> vid=0x15a2 pid=0x0071 file_name=mx6_usb_work.conf
> vid=0x15a2 pid=0x007d file_name=mx6_usb_work.conf
> vid=0x15a2 pid=0x0080 file_name=mx6_usb_work.conf
> vid=0x1fc9 pid=0x0128 file_name=mx6_usb_work.conf
> vid=0x15a2 pid=0x0076 file_name=mx7_usb_work.conf
> vid=0x1fc9 pid=0x0126 file_name=mx7ulp_usb_work.conf
> vid=0x15a2 pid=0x0041 file_name=mx51_usb_work.conf
> vid=0x15a2 pid=0x004e file_name=mx53_usb_work.conf
> vid=0x15a2 pid=0x006a file_name=vybrid_usb_work.conf
> vid=0x066f pid=0x37ff file_name=linux_gadget.conf
> vid=0x1b67 pid=0x4fff file_name=mx6_usb_sdp_spl.conf
> vid=0x0525 pid=0xb4a4 file_name=mx6_usb_sdp_spl.conf
> config file <.//mx6_usb_work.conf>
> parse .//mx6_usb_work.conf
> Trying to open device vid=0x15a2 pid=0x007d
> Interface 0 claimed
> HAB security state: development mode (0x56787856)
> == work item
> filename ../u-boot/u-boot.imx
> load_size 0 bytes
> load_addr 0x00000000
> dcd 1
> clear_dcd 0
> plug 1
> jump_mode 2
> jump_addr 0x00000000
> == end work item
> No dcd table, barker=402000d1
> 
> loading binary file(../u-boot/u-boot.imx) to 877ff400, skip=0, fsize=55c00 type=aa
> out err=-7, last_trans=0 cnt=0x4000 max=0x400 transferSize=0x0 retry=0
> out err=-7, last_trans=0 cnt=0x4000 max=0x200 transferSize=0x0 retry=1
> out err=-7, last_trans=0 cnt=0x4000 max=0x100 transferSize=0x0 retry=2
> out err=-7, last_trans=0 cnt=0x4000 max=0x80 transferSize=0x0 retry=3
> out err=-7, last_trans=0 cnt=0x4000 max=0x40 transferSize=0x0 retry=4
> out err=-7, last_trans=0 cnt=0x4000 max=0x20 transferSize=0x0 retry=5
> out err=-7, last_trans=0 cnt=0x4000 max=0x10 transferSize=0x0 retry=6
> out err=-7, last_trans=0 cnt=0x4000 max=0x8 transferSize=0x0 retry=7
> out err=-7, last_trans=0 cnt=0x4000 max=0x10 transferSize=0x0 retry=8
> out err=-7, last_trans=0 cnt=0x4000 max=0x8 transferSize=0x0 retry=9
> out err=-7, last_trans=0 cnt=0x4000 max=0x10 transferSize=0x0 retry=10
> Giving up
> DoIRomDownload failed, err=-7
> HAB security state: development mode (0x00000000)
> 
>

**Comment by gibsson** [comment] 2017-12-28 21:01
Hi,

No yours is a different issue, your U-Boot image doesn't have a DCD table:
No dcd table, barker=402000d1

So there's no way the binary can be loaded into RAM without a DCD table initializing it (or SPL previously loaded). Please check your setup.

Regards,
Gary

**Comment by ashoksowndar** [comment] 2019-11-27 13:42
Hi,

I am facing following issue with imx6ul

config file <.//imx_usb.conf>
vid=0x066f pid=0x3780 file_name=mx23_usb_work.conf
vid=0x15a2 pid=0x004f file_name=mx28_usb_work.conf
vid=0x15a2 pid=0x0052 file_name=mx50_usb_work.conf
vid=0x15a2 pid=0x0054 file_name=mx6_usb_work.conf
vid=0x15a2 pid=0x0061 file_name=mx6_usb_work.conf
vid=0x15a2 pid=0x0063 file_name=mx6_usb_work.conf
vid=0x15a2 pid=0x0071 file_name=mx6_usb_work.conf
vid=0x15a2 pid=0x007d file_name=mx6_usb_work.conf
vid=0x15a2 pid=0x0080 file_name=mx6ull_usb_work.conf
vid=0x1fc9 pid=0x0128 file_name=mx6_usb_work.conf
vid=0x15a2 pid=0x0076 file_name=mx7_usb_work.conf
vid=0x1fc9 pid=0x0126 file_name=mx7ulp_usb_work.conf
vid=0x15a2 pid=0x0041 file_name=mx51_usb_work.conf
vid=0x15a2 pid=0x004e file_name=mx53_usb_work.conf
vid=0x15a2 pid=0x006a file_name=vybrid_usb_work.conf
vid=0x066f pid=0x37ff file_name=linux_gadget.conf
vid=0x1b67 pid=0x4fff file_name=mx6_usb_sdp_spl.conf
vid=0x0525 pid=0xb4a4 file_name=mx6_usb_sdp_spl.conf
vid=0x1fc9 pid=0x012b file_name=mx8mq_usb_work.conf
vid=0x1fc9 pid=0x0134 file_name=mx8mm_usb_work.conf
vid=0x3016 pid=0x1000 file_name=mx8mm_usb_sdp_spl.conf
vid=0x3016 pid=0x1001 file_name=mx8mq_usb_sdp_spl.conf
config file <.//mx6_usb_work.conf>
parse .//mx6_usb_work.conf
Trying to open device vid=0x15a2 pid=0x007d
Interface 0 claimed
HAB security state: development mode (0x56787856)
== work item
filename uboot-imx-2015.04.imx
load_size 0 bytes
load_addr 0x00000000
dcd 1
clear_dcd 0
plug 1
jump_mode 3
jump_addr 0x00000000
== end work item
