### ISSUE TITLE
ubuntu 14.04 build error

### ISSUE THREAD

**Issue by yan2anfei** [boundarydevices/imx_usb_loader#50] opened 2016-12-09 08:34 UTC
add option -std=c99,solve the problem

**Comment by iancoolidge89** [comment] 2016-12-09 17:19
or std=gnu99

I noticed this when compiling on a raspberry pi the other day.

**Comment by gibsson** [comment] 2016-12-13 09:19
Hi,

Please specify your GCC version. I can't reproduce the issue with a standard Ubuntu 14.04 version:
$ gcc --version
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

Regards,
Gary

**Comment by pmillerchip** [comment] 2016-12-15 12:51
I have a pull request open with this change. If you want to try it, my branch is here: https://github.com/pmillerchip/imx_usb_loader/tree/ubuntu14-x64

**Comment by pmillerchip** [comment] 2016-12-15 17:39
@gibsson My gcc version is:
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

The master branch at the moment produces the following error:
cc -c imx_usb.c -o imx_usb.o -Wstrict-prototypes -Wno-trigraphs -pipe -ggdb `pkg-config --cflags libusb-1.0`  -DSYSCONFDIR='"/usr/etc"'
imx_usb.c: In function ‘do_autodetect_dev’:
imx_usb.c:533:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
   for (int retry = 0; retry < 10; retry++) {
   ^
imx_usb.c:533:3: note: use option -std=c99 or -std=gnu99 to compile your code
make: *** [imx_usb.o] Error 1

**Comment by tkisky** [comment] 2016-12-15 18:43
On 12/15/2016 9:39 AM, Peter Millerchip wrote:
> @gibsson <https://github.com/gibsson> My gcc version is:
> gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
> 
> The master branch at the moment produces the following error:
> cc -c imx_usb.c -o imx_usb.o -Wstrict-prototypes -Wno-trigraphs -pipe -ggdb |pkg-config --cflags
> libusb-1.0| -DSYSCONFDIR='"/usr/etc"'
> imx_usb.c: In function ‘do_autodetect_dev’:
> imx_usb.c:533:3: error: ‘for’ loop initial declarations are only allowed in C99 mode
> for (int retry = 0; retry < 10; retry++) {
> ^
> imx_usb.c:533:3: note: use option -std=c99 or -std=gnu99 to compile your code


I'll add a patch to move the definition of retry to the start of the function.

**Comment by gibsson** [comment] 2016-12-26 11:42
Fixed by: https://github.com/boundarydevices/imx_usb_loader/commit/c8f4ead10bcb0b1a960aa9810a8c5adb034b08c7

Regards,
Gary

**Closed by gibsson** 2016-12-26 11:42 UTC
